name: DummyCheck

on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Replace secrets in Renovate configuration
        run: |
          ls -al
          echo ${{ secrets.OCI_REGISTRY_PASSWORD }}
          sed -i "s#{{ secrets.OCI_REGISTRY_PASSWORD }}#${{ secrets.OCI_REGISTRY_PASSWORD }}#g" renovate.json
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.6
        with:
          configurationFile: config.js
          token: ${{ secrets.TOKEN }}
        env:
          TOKEN: ${{ secrets.TOKEN }}
          OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
          OCI_REGISTRY_PASSWORD: ${{ secrets.OCI_REGISTRY_PASSWORD }}
