name: DummyCheck

on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set Env
        run: export RENOVATE_AZURE_REGISTRY_PASSWORD=${{ secrets.OCI_REGISTRY_PASSWORD }}
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.6
        with:
          configurationFile: config.js
          token: ${{ secrets.TOKEN }}
        env:
          LOG_LEVEL: debug
          OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
          RENOVATE_AZURE_REGISTRY_PASSWORD: ${{ secrets.OCI_REGISTRY_PASSWORD }}
