name: Renovate bot

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate GitHub App token
        id: github_app_token
        uses: "actions/create-github-app-token@v1"
        with:
          app-id: 401207
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.7
        with:
          configurationFile: config.js
          token: ${{ steps.github_app_token.outputs.token }}
        env:
          OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
          OCI_REGISTRY_PASSWORD: ${{ secrets.OCI_REGISTRY_PASSWORD }}

